<?php

namespace Database\Seeders;

use App\DreamJobRoleModel;
use Illuminate\Database\Seeder;

class DreamJobRoleModelSeeder extends Seeder
{
    /**
     * Seed Dream Jobs role models from the current hardcoded defaults.
     * Safe to run multiple times (upserts by slug).
     */
    public function run(): void
    {
        $defaults = [
            [
                'first_name' => 'Anny',
                'last_name' => 'Tubbs',
                'slug' => 'anny-tubbs',
                'role' => 'Multimedia producer at First Move Productions',
                'image' => '/images/dream-jobs/anny-tubbs.png',
                'description1' => "Anny Tubbs' professional path began in law and evolved into multinational leadership roles, where she was tasked with delivering large-scale change in complex matrix organisations. Her focus grew from antitrust matters and sales to anti-corruption and the full spectrum of business ethics. This taught her the importance of thoughtful communication and outreach.",
                'description2' => "Anny has always been inspired by individuals whose values and skills make a positive difference. In today’s hyperconnected world - where digital and real-world issues intertwine - she seeks to leverage digital media to spotlight constructive news and encourage informed dialogue for a better future. To update her skills, Anny attended film school and completed an MSc in Journalism and Media in Europe. She co-founded a production company, directed several short documentaries, and began working with the multimedia team of a European news agency. Today, she is involved in multimedia production, content creation and educational projects that focus on digital and values-driven learning. She enjoys the fact that technology makes it possible to connect with people from all over the world.",
                'link' => 'https://www.linkedin.com/in/annytubbs/',
                'video' => 'https://www.youtube.com/embed/MUYkkR45Ky4?si=_achxuxizZ4Fs_OE',
                'pathway_map_link' => 'Career Pathway Map Anny Tubbs.pdf',
                'country' => 'be',
            ],
            [
                'first_name' => 'Magda',
                'last_name' => 'Vanzetto',
                'slug' => 'magda-vanzetto',
                'role' => 'Head of Energy Engineers at Siemens',
                'image' => '/images/dream-jobs/magda-vanzetto.png',
                'description1' => 'Magda Vanzetto is the Head of Energy Engineers at Siemens Smart Infrastructure in Sustainability Technical Unit.',
                'description2' => 'She has been active part in projects aimed at improving energy efficiency and reducing carbon footprint of multiple customers facilities.',
                'link' => 'https://www.linkedin.com/in/magda-vanzetto-42567034/',
                'video' => 'https://www.youtube.com/embed/es3l_bbGGu4?si=77C2SMDdr_-20m_s',
                'pathway_map_link' => 'C4E Career Pathway Map_MV.pdf',
                'country' => 'sz',
            ],
            [
                'first_name' => 'Roxana',
                'last_name' => 'Freusse',
                'slug' => 'roxana-freusse',
                'role' => 'Team Lead Cloud Solutions & DevOps, Scrum Master at Siemens',
                'image' => '/images/dream-jobs/roxana-freusse.png',
                'description1' => 'Roxana Freusse is the Team Lead for Cloud Solutions & DevOps and a Scrum Master at Siemens. With extensive experience in cloud technologies and agile methodologies, she excels in leading cross-functional teams to deliver innovative solutions.',
                'description2' => 'Roxana is known for her expertise in cloud infrastructure, DevOps practices, and her ability to foster collaboration and continuous improvement within her teams. Her leadership and technical skills have been instrumental in driving successful projects and enhancing operational efficiency at Siemens.',
                'link' => 'https://www.linkedin.com/in/roxanafreusse/',
                'video' => 'https://www.youtube.com/embed/1ogvTUbmudY?si=yueOQZuAH8DF7I5R',
                'pathway_map_link' => 'C4E Career Pathway Map Roxana.pdf',
                'country' => 'sz',
            ],
            [
                'first_name' => 'Vasileios',
                'last_name' => 'Linardos',
                'slug' => 'vasileios-linardos',
                'role' => 'Head of AI at ARCHEIOTHIKI SA',
                'image' => '/images/dream-jobs/vasileios-linardos.png',
                'description1' => 'Vasileios Linardos is Head of AI at Archeiothiki SA and a PhDc at the International Hellenic University in Thessaloniki, Greece, where he focuses on developing AI tools and methodologies for disaster management.',
                'description2' => 'He holds a Bachelor\'s degree in Informatics from the Athens University of Economics and Business. His expertise encompasses machine learning and deep learning applications in disaster management, with several publications on the topic. Additionally, Vasileios has expertise in large language models (LLMs), vision-language models (VLLMs), and other emerging technologies, which he applies to design and develop innovative AI solutions.',
                'link' => 'https://www.linkedin.com/in/vasileios-linardos-a18294195/',
                'video' => 'https://www.youtube.com/embed/Nubt062yw_Q?si=3FRAAin70H2XMCZ6',
                'pathway_map_link' => 'C4E Career Map Vasileios Linardos.pdf',
                'country' => 'gr',
            ],
            [
                'first_name' => 'Carole',
                'last_name' => 'Colley',
                'slug' => 'carole-colley',
                'role' => 'Bid & Proposal Management at Avanade',
                'image' => '/images/dream-jobs/carole-colley.png',
                'description1' => 'Carole Colley has accumulated over 15 years of experience in IT. Carole\'s journey into digital transformation has been marked by significant milestones. As a functional consultant, project manager and bid manager (pre-sales), Carole has successfully navigated complex projects and contributed to the growth of the organizations she has worked with.',
                'description2' => 'Carole is committed to seizing every possible opportunity to grow both professionally and personally. This dedication is evident in her focus on people management, participation in the School of Innovation, and continuous efforts to train and get certified. Carole\'s growth mindset ensures she remains at the forefront of industry developments and best practices. For Carole, commitment is not just about receiving but also about giving back to peers. As an employee network lead and vice secretary to a Work Council, Carole has demonstrated a strong commitment to fostering a supportive and collaborative work environment. Her leadership in these roles underscores the importance of community and mutual support in achieving collective success.',
                'link' => 'https://www.linkedin.com/in/carole-colley-pmp%C2%AE-a932077b/',
                'video' => 'https://www.youtube.com/embed/CUJOwRUlTpo?si=jQ7LykPZSe_KSQQJ',
                'pathway_map_link' => 'Career Pathway Map Carole Colley.pdf',
                'country' => 'fr',
            ],
            [
                'first_name' => 'Christina',
                'last_name' => 'Kiamili',
                'slug' => 'christina-kiamili',
                'role' => 'Digital Portfolio Manager at Siemens',
                'image' => '/images/dream-jobs/christina-kiamili.png',
                'description1' => 'Christina Kiamili is the Digital Portfolio Manager at Siemens.',
                'description2' => 'In her role, she oversees the development and management of digital projects, ensuring they align with the company\'s strategic objectives. Christina is known for her expertise in digital transformation, project management, and her ability to lead cross-functional teams. She focuses on driving innovation and continuous improvement within Siemens, leveraging her strong background in both agile and waterfall methodologies.',
                'link' => 'https://www.linkedin.com/in/christina-kiamili-23582a114/',
                'video' => 'https://www.youtube.com/embed/VcqM5B-iWsE?si=uh9jEpNxeL9yInXN',
                'pathway_map_link' => 'Career Pathway Map Christina Kiamili.pdf',
                'country' => 'sz',
            ],
            [
                'first_name' => 'Devon',
                'last_name' => 'Young',
                'slug' => 'devon-young',
                'role' => 'UX Design at Avanade',
                'image' => '/images/dream-jobs/devon-young.png',
                'description1' => 'Devon Young is Senior User Experience Manager at Avanade. She has over 20 years of experience in design, with a recent focus on design operations, strategy, recruiting, and nurturing talent.',
                'description2' => 'She believes that great design outcomes stem from a great team environment. Her passion for design began in high school in Missouri, USA where she created CD covers and T-shirts. Encouraged by her father, she pursued a career in design, studying Graphic Design at university.',
                'link' => 'https://www.linkedin.com/in/devoneyoung/',
                'video' => 'https://www.youtube.com/embed/ZmEc9RKy-MI?si=jQnFHpPXQm5Usa-Y',
                'pathway_map_link' => 'C4E Career Pathway Map - Devon Young.pdf',
                'country' => 'uk',
            ],
            [
                'first_name' => 'Paula',
                'last_name' => 'Panarra',
                'slug' => 'paula-panarra',
                'role' => 'General Manager at Avanade UK & Ireland',
                'image' => '/images/dream-jobs/paula-panarra.png',
                'description1' => 'Paula Panarra is the General Manager at Avanade UK & Ireland. Previously, she served as the Global Business Applications Sales Lead for Retail and Consumer Goods at Microsoft Portugal, where she was the General Director from 2016. In this role, she guided the organization through the digital transformation of the Portuguese economy, empowering people and organizations with technology.',
                'description2' => 'She joined Microsoft in 2010 as the CMO Lead, later becoming the Marketing & Operations Lead in 2013, and the Public Sector Lead in 2016. Before her tenure at Microsoft, Paula spent 15 years at Procter & Gamble Portugal and Iberia, holding various roles in Finance and Marketing, including Corporate Marketing Director, Finance Group Director, and Communication Director. Paula graduated in Chemical Engineering from the Instituto Superior Técnico in 1994. She is known for her optimism, solution-oriented mindset, and commitment to doing the right thing. Outside of her professional life, she is a proud mother of three daughters, an avid reader, a music lover, and an adventurous traveler.',
                'link' => 'https://www.linkedin.com/in/paulapanarra/',
                'video' => 'https://www.youtube.com/embed/z5NfcNKMiMk?si=P5CIKlqeft_z0mGN',
                'pathway_map_link' => '',
                'country' => 'sp',
            ],
            [
                'first_name' => 'Ribka',
                'last_name' => 'Balakrishnan',
                'slug' => 'ribka-balakrishnan',
                'role' => 'Mechanical Design Engineer at WSAudiology',
                'image' => '/images/dream-jobs/ribka-balakrishnan.png',
                'description1' => 'Ribka Balakrishnan is a Mechanical Design Engineer working at WSAudiology.',
                'description2' => 'She is deeply involved in the research and development of hearing aids, and enjoys the hands-on aspects of her role, including prototyping and testing, which allow her to work closely with the products. She is also passionate about advocating for and supporting girls and women in all parts of society.',
                'link' => 'https://www.linkedin.com/in/ribka-balakrishnan/',
                'video' => 'https://www.youtube.com/embed/17X3-okWYhc?si=xyToCplHCQcbU4ex',
                'pathway_map_link' => 'Career Pathway Map Ribka Balakrishnan.pdf',
                'country' => 'da',
            ],
            [
                'first_name' => 'Jeevantika',
                'last_name' => 'Lingalwar',
                'slug' => 'jeevantika-lingalwar',
                'role' => 'Cloud Solution Architect at Microsoft',
                'image' => '/images/dream-jobs/jeevantika-lingalwar.png',
                'description1' => 'Jeevantika Lingalwar is a Partner Solution Architect at Microsoft, TEDx speaker, and founder of International Women in Tech, leading a community of over 7000 members.',
                'description2' => 'With M.Sc. degree in Cloud Computing and B.E in Computer Science Engineering, she is passionate about Women in Technology and Diversity & Inclusion. Jeevantika mentors\' young minds about AI and hosts the podcast &quot;The Unplanned Journey,&quot; celebrating women\'s resilience. She has been recognized as a Top Voice of the New Era of Leaders 2024, awarded the WomenTech Global Ambassador Award in 2021, and is a finalist for many awards in Ireland.',
                'link' => 'https://www.linkedin.com/in/jeevantika-lingalwar/',
                'video' => 'https://www.youtube.com/embed/98QFrA-mJkA?si=2d2wS4ll4tnDhO8F',
                'pathway_map_link' => 'Career Pathway Map Jeevantika Lingalwar.pdf',
                'country' => 'ei',
            ],
            [
                'first_name' => 'Dominik',
                'last_name' => 'Bolerác',
                'slug' => 'dominik-bolerác',
                'role' => 'Application Developer at Zurich Insurance Company',
                'image' => '/images/dream-jobs/dominik-bolerác.png',
                'description1' => 'Dominik\'s professional journey began during his university studies at the international company Zurich Insurance. He participated in a rotational internship program, which allowed students to experience working in various departments within the company - including risk management, actuarial services, and pricing & analytics.',
                'description2' => 'Currently, Dominik works full-time as an application developer in the risk management department, where he is responsible for day-to-day production tasks and creating API packages that help automate internal processes. He works with programming languages (R, SQL, DAX) and data visualization tools (Power BI) on a daily basis. Dominik studied mathematics in high school and continued to pursue it at the university level. In his free time, he plays drums in an ABBA tribute band, traveling all over the world thanks to his flexible work. He is also very passionate about running and holds a professional running coaching certificate, which allows him to share his knowledge with colleagues, his athletes, and other passionate runners.',
                'link' => 'https://www.linkedin.com/in/dominik-boler%C3%A1c-39b333209/',
                'video' => 'https://www.youtube.com/embed/hNuyHzFE2J8?si=qjghlBjFnd4DKh6J',
                'pathway_map_link' => 'C4E Career Pathway Map - Dominik Bolerac.pdf',
                'country' => 'lo',
            ],
            [
                'first_name' => 'Sara',
                'last_name' => 'Mathews',
                'slug' => 'sara-mathews',
                'role' => 'Group Responsible AI Manager at The Adecco Group',
                'image' => '/images/dream-jobs/sara-mathews.png',
                'description1' => 'Sarah Mathews is the Group Responsible AI Manager at The Adecco Group. She is responsible for operationalizing the group\'s Responsible AI Principles by establishing governance, guidelines, and change management processes, as well as co-leading the implementation of the AI Act. With a wealth of experience in leading global AI initiatives, she is renowned for her expertise in integrating ethical and inclusive AI practices within the company.',
                'description2' => 'Sarah\'s dual background in Human Resources and AI gives her a unique perspective on HR-related AI systems worldwide. She excels at engaging stakeholders and bridging the gap between business and development teams, ensuring AI projects are scaled strategically with a business-driven and human-centric approach. Passionate about fostering knowledge-sharing communities, Sarah actively promotes best practices in AI across The Adecco Group\'s brands and countries. Beyond her professional role, Sarah is dedicated to volunteering efforts that encourage women to enter the field of Data Science. She also mentors aspiring female leaders, helping them navigate and build successful careers in tech.',
                'link' => 'https://www.linkedin.com/in/sarah-mathews-87b481122/',
                'video' => 'https://www.youtube.com/embed/-rxlrF3Mt8A?si=4DMHeKV8LZS26_5x',
                'pathway_map_link' => '',
                'country' => 'gm',
            ],
            [
                'first_name' => 'Paraskevi',
                'last_name' => 'Nomikou',
                'slug' => 'paraskevi-nomikou',
                'role' => 'Marine Geologist and an Assistant Professor at the Department of Geology and Geoenvironment at the National and Kapodistrian University of Athens',
                'image' => '/images/dream-jobs/paraskevi-nomikou.png',
                'description1' => 'Paraskevi Nomikou is a marine geologist and an Assistant Professor at the Department of Geology and Geoenvironment at the National and Kapodistrian University of Athens, Greece. She specializes in the study of underwater volcanoes and seafloor processes. With extensive experience in marine volcanic activity, she has participated in over 70 oceanographic cruises, focusing on submarine volcanism, mud volcanoes, landslides, and seafloor mineral deposits',
                'description2' => 'Paraskevi has played a significant role in evaluating potential hazards associated with volcanic activity at the Santorini volcano and has been involved in mapping the seafloor of ocean core complexes and offshore volcanoes. She is also dedicated to educating and inspiring young women to pursue careers in oceanography through her lectures and innovative marine technologies',
                'link' => 'https://www.linkedin.com/in/paraskevi-nomikou-325393203/',
                'video' => 'https://www.youtube.com/embed/7M5Gie2rRt4?si=mqaOkY9C29KxgRUO',
                'pathway_map_link' => '',
                'country' => 'gr',
            ],
        ];

        foreach ($defaults as $index => $row) {
            DreamJobRoleModel::updateOrCreate(
                ['slug' => $row['slug']],
                [
                    'first_name' => $row['first_name'],
                    'last_name' => $row['last_name'],
                    'role' => $row['role'],
                    'image' => $row['image'],
                    'country' => $row['country'],
                    'description1' => $row['description1'],
                    'description2' => $row['description2'],
                    'link' => $row['link'],
                    'video' => $row['video'],
                    'pathway_map_link' => $row['pathway_map_link'] !== '' ? $row['pathway_map_link'] : null,
                    'pathway_title' => $row['pathway_title'] ?? 'Explore Career Pathway',
                    'pathway_cta_text' => $row['pathway_cta_text'] ?? 'Career Pathway Map',
                    'position' => $index,
                    'active' => true,
                ]
            );
        }

        $this->command->info('Dream Jobs role models seeded/updated. You can now manage them in Nova.');
    }
}
