<?php

namespace Database\Seeders;

use App\MatchmakingProfile;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Carbon\Carbon;

class MatchmakingProfilesSeeder extends Seeder
{
    public function run()
    {
        $records = [
            [
                'start_time'  => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 10:25:26')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 10:30:55')->toDateTimeString(),
                'avatar'     => '/images/matchmaking-tool/individuals/sara-buonporto.jpeg',
                'email'      => 'sara.buonporto@idcert.io',
                'get_email_from'      => null,
                'email_via_linkedin'  => false,
                'first_name' => 'Sara',
                'last_name'  => 'Buonporto',
                'slug'       => Str::slug('Sara Buonporto'),
                'languages'  => ['English', 'Italian', 'Spanish'],
                'job_title'  => 'Chief Executive',
                'linkedin'   => 'https://www.linkedin.com/in/sara-buonporto-60815231a/',
                'organisation_type' => ['EdTech', 'INTERNATIONAL CERTIFICATION'],
                'organisation_name' => 'IDCERT',
                'website'    => 'https://it.idcert.io',
                'location'   => 'andria, Italy',
                'country'    => 'IT',
                'time_commitment' => ['Short time', 'Outside business hours'],
                'can_start_immediately' => true,
                'why_volunteering' => 'I’m volunteering because I believe in the power of education to shape the future. Sharing my digital skills and experience can help inspire students, show them real-world applications of what they’re learning, and encourage them to explore careers in technology. It’s a meaningful way to give back and support the next generation.',
                'format'     => 'Both',
                'support_activities' => [
                    'everything apart from hackathons and curricula',
                    'is not giving me the possibility to select more than one'
                ],
                'is_use_resource' => false,
                'want_updates'    => true,
                'description'     => 'IDCERT specializes in delivering certified digital skills training aligned with European standards. We operate internationally and collaborate with public institutions, schools, and ministries across multiple countries. Our programs are designed for both educators and students, and we provide multilingual support, interoperable digital credentials (Open Badges), and scalable solutions that adapt to diverse educational systems.',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_time'  => Carbon::createFromFormat('n/j/y H:i:s', '5/19/25 19:07:32')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/19/25 19:12:25')->toDateTimeString(),
                'avatar'     => null,
                'email'      => '',
                'get_email_from'     => 'Reached out via Linkedin',
                'email_via_linkedin' => true,
                'first_name' => 'India',
                'last_name'  => 'Vera',
                'slug'       => Str::slug('India Vera'),
                'languages'  => ['English', 'Spanish'],
                'job_title'  => 'Alfabetizadora digital',
                'linkedin'   => 'https://www.linkedin.com/in/india-vera-bustamante-345511276',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'Don Benito',
                'website'    => '',
                'location'   => 'Spain',
                'country'    => 'ES',
                'time_commitment' => ['Short time', 'One-off'],
                'can_start_immediately' => true,
                'why_volunteering' => 'I am volunteering because I believe that digital literacy and coding are essential skills for the future. I want to contribute to making technology education more accessible and engaging, especially for young people and beginners. Volunteering for Code Week allows me to share my passion for coding, inspire others, and support my community in developing the skills they need to thrive in a digital world. It’s also a great opportunity to collaborate, learn from others, and be part of a wider European initiative promoting innovation and creativity',
                'format'     => 'Both',
                'support_activities' => ['Delivering webinars'],
                'is_use_resource' => false,
                'want_updates'    => true,
                'description'     => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_time'  => Carbon::createFromFormat('n/j/y H:i:s', '5/20/25 5:51:52')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/20/25 6:16:11')->toDateTimeString(),
                'avatar'     => null,
                'email'      => '',
                'get_email_from'     => null,
                'email_via_linkedin' => false,
                'first_name' => 'Roman',
                'last_name'  => 'Murzhak',
                'slug'       => Str::slug('Roman Murzhak 1'),
                'languages'  => ['Ukrainian', 'English with translator'],
                'job_title'  => 'Head of information eco-studio',
                'linkedin'   => '',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'Kherson Centre of children and youth creativity',
                'website'    => 'https://hcdut.ks.ua/',
                'location'   => 'Ukraine, Kherson',
                'country'    => 'UA',
                'time_commitment' => ['Outside business hours', 'Short time'],
                'can_start_immediately' => true,
                'why_volunteering' => 'Good afternoon. Greetings from Ukraine. My name is Roman. For many years, I have been conducting an awareness-raising campaign on media literacy and digital literacy for my students and other educational institutions. I like to help and teach students digital skills, personal data protection, fact-checking, and information hygiene. This academic year alone, I have held more than 160 events involving 2600 students. I also started helping adults to acquire digital skills. Thank you for the opportunity to teach as many children as possible.',
                'format'     => 'Online/Remote only',
                'support_activities' => ['Conducting seminars', 'trainings', 'webinars', 'online event panorama'],
                'is_use_resource' => true,
                'want_updates'    => true,
                'description'     => 'I teach a wide range of topics, namely: Information hygiene, cyber fraud (phishing, vishing, smishing, shoulder surfing, catfishing), personal data protection, fact-checking, disinformation, manipulation, digital etiquette and netiquette, copyright on the Internet.',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_time'  => Carbon::createFromFormat('n/j/y H:i:s', '5/20/25 13:02:53')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/20/25 13:08:22')->toDateTimeString(),
                'avatar'     => null,
                'email'      => '',
                'get_email_from'     => 'Reached out to her school',
                'email_via_linkedin' => false,
                'first_name' => 'Giedre',
                'last_name'  => 'Sudniute',
                'slug'       => Str::slug('Giedre Sudniute'),
                'languages'  => ['Lithuanian'],
                'job_title'  => 'teacher',
                'linkedin'   => 'Giedrė Sudniutė',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'Utena Daunishkis Gymnasia',
                'website'    => '',
                'location'   => 'Utena',
                'country'    => 'LT',
                'time_commitment' => ['Outside business hours', 'Short time'],
                'can_start_immediately' => true,
                'why_volunteering' => 'I am interested in innovations.',
                'format'     => 'Online/Remote only',
                'support_activities' => ['Delivering webinars'],
                'is_use_resource' => true,
                'want_updates'    => true,
                'description'     => ':) ',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_time'        => Carbon::createFromFormat('n/j/y H:i:s', '5/20/25 14:23:44')->toDateTimeString(),
                'completion_time'   => Carbon::createFromFormat('n/j/y H:i:s', '5/20/25 14:44:30')->toDateTimeString(),
                'avatar'            => null,
                'email'             => '',
                'get_email_from'    => 'Reached out via Facebook',
                'email_via_linkedin' => false,
                'first_name'        => 'Sonata',
                'last_name'         => 'Jonauskienė',
                'slug'              => Str::slug('Sonata Jonauskienė'),
                'languages'         => ['Lithuanian'],
                'job_title'         => 'Physical Education Teacher (Kindergarten)',
                'linkedin'          => '',
                'facebook'          => 'https://www.facebook.com/sonata.jonauskiene',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'Kaunas Kindergarten "Pelėdžiukas"',
                'website'           => 'https://kaunopeledziukas.lt/',
                'location'          => 'Lithuania, Kaunas',
                'country'           => 'LT',
                'time_commitment'   => ['Short time', 'Outside business hours'],
                'can_start_immediately'          => true,
                'why_volunteering'               => 'I am an expert teacher and an active, dedicated member of the eTwinning platform. I have successfully implemented several international eTwinning projects, especially focusing on coding and digital education. All of my projects have been awarded National and European Quality Labels, which reflect their high quality and impact. I volunteer because I am inspired by sharing experiences, collaborating with others, and the opportunity to grow together. I am passionate about educational innovation, constantly looking for new and creative approaches in my work. I truly believe that meaningful change starts with personal initiative. For me, volunteering is not only about helping others – it is also about personal development, inspiration, and contributing to the improvement of modern education.',
                'format'            => 'Online/Remote only',
                'support_activities' => ['Mentoring students or educators'],
                'is_use_resource'   => true,
                'want_updates'      => true,
                'description'       => 'I have an English language barrier. I would prefer an activity for Lithuanian teachers, or an activity where I can use online translation programs (Google translate). I am a Teacher who likes to write more than speak.',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'start_time'        => Carbon::createFromFormat('n/j/y H:i:s', '5/20/25 20:51:07')->toDateTimeString(),
                'completion_time'   => Carbon::createFromFormat('n/j/y H:i:s', '5/20/25 21:01:29')->toDateTimeString(),
                'avatar'            => null,
                'email'             => 'ldvilnele@yahoo.com',
                'get_email_from'    => null,
                'email_via_linkedin' => false,
                'first_name'        => 'Vilma',
                'last_name'         => 'Sobolienė',
                'slug'              => Str::slug('Vilma Sobolienė'),
                'languages'         => ['Lithuanian'],
                'job_title'         => 'Teacher',
                'linkedin'          => 'https://www.linkedin.com/in/vilma-sobolien%C4%97-4b342113a/',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'Kaunas kindergarten “Vilnelė”',
                'website'           => 'https://www.darzelisvilnele.lt/',
                'location'          => 'Kaunas, Lithuania',
                'country'           => 'LT',
                'time_commitment'   => ['Outside business hours', 'Short time'],
                'can_start_immediately'          => true,
                'why_volunteering'               => 'I am volunteering because I am interested in activities related to children\'s digital literacy. I want to contribute to helping young people develop their digital skills and discover the world of technology. I believe that early exposure to coding and digital tools can inspire creativity, critical thinking, and open up more opportunities for their future. It is also important to me to give back to the community by supporting the development of skills that are increasingly essential in today’s world.',
                'format'            => 'Both',
                'support_activities' => ['Mentoring students or educators'],
                'is_use_resource'   => true,
                'want_updates'      => true,
                'description'       => 'I have a strong interest in working with younger students and introducing them to basic digital skills in a fun and engaging way. I am open to both online and in-person formats and can adapt to the needs of different schools. I am especially passionate about promoting equal access to digital education for all children, regardless of their background.',
                'agree_to_be_contacted_for_feedback' => false,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'start_time'        => Carbon::createFromFormat('n/j/y H:i:s', '5/21/25 13:40:56')->toDateTimeString(),
                'completion_time'   => Carbon::createFromFormat('n/j/y H:i:s', '5/21/25 13:51:32')->toDateTimeString(),
                'avatar'            => null,
                'email'             => 'dianutes@gmail.com',
                'get_email_from'    => null,
                'email_via_linkedin' => false,
                'first_name'        => 'Diana',
                'last_name'         => 'Bazevičienė',
                'slug'              => Str::slug('Diana Bazevičienė'),
                'languages'         => ['English', 'Lithuanian'],
                'job_title'         => 'Teacher',
                'linkedin'          => '',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'Jonavos vaikų lopšelis-darželis ,Bitutė',
                'website'           => '',
                'location'          => 'Lithuania',
                'country'           => 'LT',
                'time_commitment'   => ['Outside business hours', 'Short time'],
                'can_start_immediately'          => true,
                'why_volunteering'               => 'I often organize and personally take part in international eTwinning projects, give presentations at conferences, and share best practices in Lithuania. For me, it\'s an opportunity to grow, share knowledge, build new connections, and improve myself.',
                'format'            => 'Online/Remote only',
                'support_activities' => ['Delivering workshops or training'],
                'is_use_resource'   => true,
                'want_updates'      => true,
                'description'       => 'What is most relevant to me are students aged 5–7 and their teachers, as well as younger age groups.',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'start_time'        => Carbon::createFromFormat('n/j/y H:i:s', '5/21/25 19:13:16')->toDateTimeString(),
                'completion_time'   => Carbon::createFromFormat('n/j/y H:i:s', '5/21/25 19:32:22')->toDateTimeString(),
                'avatar'            => null,
                'email'             => 'sakiene@gmail.com',
                'get_email_from'    => null,
                'email_via_linkedin' => false,
                'first_name'        => 'Lina',
                'last_name'         => 'Sakienė',
                'slug'              => Str::slug('Lina Sakienė'),
                'languages'         => ['English', 'Lithuanian'],
                'job_title'         => 'Speech therapist',
                'linkedin'          => '',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'Kindergarten "Eglutė", Telšiai. Lithuania',
                'website'           => '',
                'location'          => 'Telšiai, Lithuania',
                'country'           => 'LT',
                'time_commitment'   => ['Outside business hours', 'Short time'],
                'can_start_immediately'          => true,
                'why_volunteering'               => 'A desire for personal and professional growth. I want to broaden my horizons and discover new interests, as well as enjoy the process and share knowledge with others.',
                'format'            => 'Online/Remote only',
                'support_activities' => ['I think I could try a few things that were mentioned before'],
                'is_use_resource'   => true,
                'want_updates'      => true,
                'description'       => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'start_time'        => Carbon::createFromFormat('n/j/y H:i:s', '5/26/25 10:13:31')->toDateTimeString(),
                'completion_time'   => Carbon::createFromFormat('n/j/y H:i:s', '5/26/25 10:17:28')->toDateTimeString(),
                'avatar'            => null,
                'email'             => 'ruben.mancera@gmail.com',
                'get_email_from'    => null,
                'email_via_linkedin' => false,
                'first_name'        => 'Rubén Darío',
                'last_name'         => 'Mancera Morán',
                'slug'              => Str::slug('Rubén Darío Mancera Morán'),
                'languages'         => ['English', 'Spanish'],
                'job_title'         => 'AUPEX',
                'linkedin'          => 'Coordinador',
                'organisation_type' => [
                    'Education/Training Provider',
                    'Non-Governmental Organisation (NGO)',
                    'Academic Institution / Research Organisation'
                ],
                'organisation_name' => '',
                'website'           => 'https://www.espaciosdigitalex.org/codeweek/',
                'location'          => 'España',
                'country'           => 'ES',
                'time_commitment'   => ['Outside business hours', 'Short time'],
                'can_start_immediately'          => true,
                'why_volunteering'               => 'I love Programming and computers. I am programming teacher.',
                'format'            => 'Both',
                'support_activities' => ['Delivering workshops or training'],
                'is_use_resource'   => true,
                'want_updates'      => true,
                'description'       => 'I am the coordinator of <a class="text-dark-blue" href="https://www.espaciosdigitalex.org/codeweek">Codeweek in AUPEX</a> in our project Espacios Digitalex: Red de Centros de Competencias Digitales de Extremadura',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'start_time'        => Carbon::createFromFormat('n/j/y H:i:s', '5/28/25 15:50:56')->toDateTimeString(),
                'completion_time'   => Carbon::createFromFormat('n/j/y H:i:s', '5/28/25 16:06:59')->toDateTimeString(),
                'avatar'            => null,
                'email'             => 'romanmurzhak@gmail.com',
                'get_email_from'    => null,
                'email_via_linkedin' => false,
                'first_name'        => 'Roman',
                'last_name'         => 'Murzhak',
                'slug'              => Str::slug('Roman Murzhak'),
                'languages'         => ['Ukrainian', 'English with translator'],
                'job_title'         => 'Head of the club',
                'linkedin'          => '',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'Kherson Centre of children and youth creativity',
                'website'           => '',
                'location'          => 'Ukraine. Kherson',
                'country'           => 'UA',
                'time_commitment'   => ['Outside business hours', 'Short time'],
                'can_start_immediately'          => true,
                'why_volunteering'               => 'For many years, I have been conducting media literacy awareness campaigns for students of educational institutions. I teach courses on digital literacy, personal data protection, digital hygiene, and disinformation. Thank you for the opportunity to hold events for even more people.',
                'format'            => 'Online/Remote only',
                'support_activities' => ['Conducting seminars', 'Trainings', 'Webinars'],
                'is_use_resource'   => true,
                'want_updates'      => true,
                'description'       => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'start_time'        => Carbon::createFromFormat('n/j/y H:i:s', '5/28/25 18:55:09')->toDateTimeString(),
                'completion_time'   => Carbon::createFromFormat('n/j/y H:i:s', '5/28/25 19:00:08')->toDateTimeString(),
                'avatar'            => null,
                'email'             => 'costeaagnes211@gmail.com',
                'get_email_from'    => null,
                'email_via_linkedin' => false,
                'first_name'        => 'Costea',
                'last_name'         => 'Agnes Ildico',
                'slug'              => Str::slug('Costea Agnes Ildico'),
                'languages'         => ['German', 'Hungarian', 'Romanian', 'English'],
                'job_title'         => 'Profesor educație timpurie',
                'linkedin'          => '',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'Liceul Tehnologic Stănescu Valerian Tirnava',
                'website'           => '',
                'location'          => 'Tirnava, Sibiu, România',
                'country'           => 'RO',
                'time_commitment'   => ['One-off', 'Short time'],
                'can_start_immediately'          => true,
                'why_volunteering'               => 'Îmi place să ajut comunitatea și colegii',
                'format'            => 'Online/Remote only',
                'support_activities' => ['Mentoring students or educators'],
                'is_use_resource'   => true,
                'want_updates'      => true,
                'description'       => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],
            [
                'start_time'        => Carbon::createFromFormat('n/j/y H:i:s', '6/2/25 8:52:31')->toDateTimeString(),
                'completion_time'   => Carbon::createFromFormat('n/j/y H:i:s', '6/2/25 8:59:45')->toDateTimeString(),
                'avatar'            => null,
                'email'             => 'sancharide.ju@gmail.com',
                'get_email_from'    => null,
                'email_via_linkedin' => false,
                'first_name'        => 'Sanchari',
                'last_name'         => 'De',
                'slug'              => Str::slug('Sanchari De'),
                'languages'         => ['English', 'Swedish'],
                'job_title'         => 'ICT Coordinator',
                'linkedin'          => 'https://www.linkedin.com/in/sanchari-de-phd-a2419423/',
                'organisation_type' => ['Education/Training Provider', 'Public Sector Organisation / Government Agency'],
                'organisation_name' => 'Malmö International School',
                'website'           => '',
                'location'          => 'Malmö, Sweden',
                'country'           => 'SE',
                'time_commitment'   => ['One-off', 'Short time'],
                'can_start_immediately'          => true,
                'why_volunteering'               => 'I am willing to contribute to the integration of ICT skills into pedagogical activities following 21st century skills and merge the digital divide.',
                'format'            => 'Both',
                'support_activities' => ['Deliver workshop', 'Mentor teachers and students', 'Be guest speaker', 'Deliver webinars'],
                'is_use_resource'   => true,
                'want_updates'      => true,
                'description'       => 'I am an expert of the digitalisation process. I can help with making digital transformation plans for schools.',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at'        => now(),
                'updated_at'        => now(),
            ],

            // organisations
            [
                'type' => 'organisation',
                'start_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 9:08:01')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 9:15:42')->toDateTimeString(),
                'avatar' => '/images/matchmaking-tool/organisations/global-libraries-bulgaria-foundaation.png',
                'email' => 'foundation@glbulgaria.net',
                'organisation_name' => 'Global Libraries Bulgaria Foundaation',
                'slug'              => Str::slug('Global Libraries Bulgaria Foundaation'),
                'website' => 'https://www.glbulgaria.bg',
                'organisation_type' => ['Non-Governmental Organisation (NGO)'],
                'country' => 'BG',
                'organisation_mission' => 'Our mission is to contribute to the inclusion of the Bulgarian public in the global digital community, to raise their quality of life, and to promote civic participation.',
                'support_activities' => [
                    'Delivering workshops or training',
                    'Providing learning resources or curricula'
                ],
                'interested_in_school_collaboration' => 'Maybe, I would like more details',
                'target_school_types' => ['Primary Schools'],
                'digital_expertise_areas' => ['Coding and programming', 'Cybersecurity'],
                'want_updates' => true,
                'description' => 'GLBF, over the years, has promoted Code Week in Bulgaria through the network of public libraries.',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'organisation',
                'start_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 9:24:01')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 9:27:44')->toDateTimeString(),
                'avatar' => '/images/matchmaking-tool/organisations/european-grants-international-academy.png',
                'email' => 'info@egina.eu',
                'organisation_name' => 'European Grants International Academy',
                'slug'              => Str::slug('European Grants International Academy'),
                'website' => 'https://www.egina.eu/',
                'organisation_type' => ['Education/Training Provider'],
                'country' => 'IT',
                'organisation_mission' => 'EGInA – European Grants International Academy – has been founded in 2012 in Foligno, in the green heart of Italy, thanks to Fabiola Acciarri’s experience in the training field and Altheo Valentini’s passion for innovation and social change. The agency, accredited by the Umbria Region for vocational training and certification of competences, represents today one of the main stakeholders in the field of local, national, and European initiatives design and implementation, relying on the cooperation of numerous experts in the fields of education, social innovation, cultural heritage and digital transformation.',
                'support_activities' => [
                    'Delivering workshops or training',
                    'Mentoring students or educators',
                    'Running competitions or hackathons',
                    'Providing learning resources or curricula',
                    'Offering internships or work placements',
                    'Organizing guest speaker sessions',
                ],
                'interested_in_school_collaboration' => 'Yes, definitely',
                'target_school_types' => [
                    'Primary Schools',
                    'Secondary Schools',
                    'Higher Education Institutions (Universities/Colleges)',
                    'Vocational and Technical Schools'
                ],
                'digital_expertise_areas' => [
                    'STEM/STEAM education',
                    'Digital Education and EdTech'
                ],
                'want_updates' => true,
                'description' => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'organisation',
                'start_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 9:43:58')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 9:47:18')->toDateTimeString(),
                'avatar' => '/images/matchmaking-tool/organisations/polo-digital.png',
                'avatar_dark' => true,
                'email' => 'hola@polodigital.eu',
                'organisation_name' => 'Polo digital',
                'slug'              => Str::slug('Polo digital'),
                'website' => 'www.polodigital.eu',
                'organisation_type' => ['Public Sector Organisation / Government Agency'],
                'country' => 'ES',
                'organisation_mission' => 'We are a public innovation hub depending on the City Council of Málaga. We host start ups and scale ups in deep tech and XR, facilitating them all the resources they need to grow: talent, equipment, incubation programa, venue for events…',
                'support_activities' => [
                    'Running competitions or hackathons',
                    'Organizing guest speaker sessions',
                    'Offering internships or work placements',
                    'Delivering workshops or training'
                ],
                'interested_in_school_collaboration' => 'Yes, definitely',
                'target_school_types' => [
                    'Higher Education Institutions (Universities/Colleges)',
                    'Vocational and Technical Schools'
                ],
                'digital_expertise_areas' => [
                    'Digital Education and EdTech',
                    'Cybersecurity',
                    'Artificial Intelligence & Machine Learning',
                    'STEM/STEAM education',
                    'Coding and programming'
                ],
                'want_updates' => true,
                'description' => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'organisation',
                'start_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 10:18:40')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 10:24:44')->toDateTimeString(),
                'avatar' => '/images/matchmaking-tool/organisations/idcert-srl-societa-benefit.png',
                'avatar_dark' => true,
                'email' => 'info@idcert.io',
                'organisation_name' => 'IDCERT SRL SOCIETÀ BENEFIT',
                'slug'              => Str::slug('IDCERT SRL SOCIETÀ BENEFIT'),
                'website' => 'https://it.idcert.io',
                'organisation_type' => ['EdTech', 'INTERNATIONAL CERTIFICATION'],
                'country' => 'IT',
                'organisation_mission' => 'IDCERT srl Società Benefit is a European-certified digital skills training provider, accredited under ISO 9001, ISO/IEC 27001, ISO/IEC 27017, ISO 29993, ISO 29994, and operates in compliance with UNI CEI EN ISO/IEC 17024 for personnel certification. The company is registered in the Italian National Research Registry (MIUR) and participates in major European alliances such as 1EdTech, ESSA (European Software Skills Alliance), and the Coalition for Competitive Digital Markets. IDCERT is an AWS Authorized Training Partner, a recognized provider on the Syllabus PA platform, and a National Youth Card partner. It is also accredited by the Ministry of Education for the training of school staff and leaders.',
                'support_activities' => [
                    'Delivering workshops or training',
                    'Mentoring students or educators',
                    'Running competitions or hackathons',
                    'Providing learning resources or curricula',
                    'Organizing guest speaker sessions',
                    'Offering internships or work placements'
                ],
                'interested_in_school_collaboration' => 'Yes, definitely',
                'target_school_types' => [
                    'Higher Education Institutions (Universities/Colleges)',
                    'Vocational and Technical Schools',
                    'Secondary Schools',
                    'Public sector'
                ],
                'digital_expertise_areas' => [
                    'Digital Education and EdTech',
                    'Cybersecurity',
                    'Artificial Intelligence & Machine Learning',
                    'STEM/STEAM education',
                    'Coding and programming',
                    'canvaedu, digital animator, social media manager'
                ],
                'want_updates' => true,
                'description' => 'Yes, IDCERT specializes in delivering certified digital skills training aligned with European standards. We operate internationally and collaborate with public institutions, schools, and ministries across multiple countries. Our programs are designed for both educators and students, and we provide multilingual support, interoperable digital credentials (Open Badges), and scalable solutions that adapt to diverse educational systems.',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'organisation',
                'start_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 10:42:27')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/16/25 10:59:24')->toDateTimeString(),
                'avatar' => '/images/matchmaking-tool/organisations/opengroup.webp',
                'avatar_dark' => true,
                'email' => 'amministrazione@opengroup.eu',
                'organisation_name' => 'Open Group',
                'slug'              => Str::slug('Open Group'),
                'website' => 'https://opengroup.eu/',
                'organisation_type' => ['Non-Governmental Organisation (NGO)'],
                'country' => 'IT',
                'organisation_mission' => 'Proponiamo laboratori di introduzione al pensiero computazionale nelle scuole dell’infanzia e primarie, a partire dai 5 anni. I percorsi prevedono l’utilizzo di diverse metodologie: coding unplugged, tinkering e robotica educativa, programmazione a blocchi con Scratch e Octostudio. Il nostro approccio parte dal lavoro teorico sviluppato dal gruppo di ricerca Lifelong Kindergarden del MIT di Boston.',
                'support_activities' => [
                    'Delivering workshops or training',
                    'Mentoring students or educators',
                    'Organizing guest speaker sessions'
                ],
                'interested_in_school_collaboration' => 'Maybe, I would like more details',
                'target_school_types' => [
                    'Primary Schools', 'Secondary Schools'
                ],
                'digital_expertise_areas' => [
                    'STEM/STEAM education',
                    'Coding and programming',
                    'Digital Education and EdTech',
                    'Artificial Intelligence & Machine Learning'
                ],
                'want_updates' => true,
                'description' => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'organisation',
                'start_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/22/25 9:43:51')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '5/26/25 8:04:38')->toDateTimeString(),
                'avatar' => '/images/matchmaking-tool/organisations/mickunulopselis-darzelis.jpg',
                'email' => 'mickunulopselis.darzelis@gmail.com ',
                'organisation_name' => 'Vilniaus r. Mickūnų vaikų lopšelis-darželis',
                'slug'              => Str::slug('Vilniaus r. Mickūnų vaikų lopšelis-darželis'),
                'website' => 'https://www.lopselis.darzelis.mickunai.vilniausr.lm.lt/',
                'organisation_type' => ['Preschool'],
                'country' => 'LT',
                'organisation_mission' => '',
                'support_activities' => ['Offering internships or work placements'],
                'interested_in_school_collaboration' => 'Maybe, I would like more details',
                'target_school_types' => ['Preprimary school'],
                'digital_expertise_areas' => ['STEM/STEAM education'],
                'want_updates' => true,
                'description' => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'type' => 'organisation',
                'start_time' => Carbon::createFromFormat('n/j/y H:i:s', '6/2/25 22:23:38')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '6/2/25 22:33:06')->toDateTimeString(),
                'avatar' => '/images/matchmaking-tool/organisations/datorium.png',
                'avatar_dark' => true,
                'email' => 'info@datorium.eu',
                'organisation_name' => 'Datorium',
                'slug'              => Str::slug('Datorium'),
                'website' => 'https://datorium.eu, https://datorium.ai',
                'organisation_type' => ['EdTech'],
                'country' => 'LV',
                'organisation_mission' => 'Datorium is an innovative EdTech organisation. Read more about Datorium: <a class="text-dark-blue" href="https://www.linkedin.com/company/datorium">Co-founders Angela Jafarova and Elchin Jafarov</a> (both active in codeweek)',
                'support_activities' => [
                    'Delivering workshops or training',
                    'Running competitions or hackathons',
                    'Providing learning resources or curricula',
                    'Organizing guest speaker sessions'
                ],
                'interested_in_school_collaboration' => 'Maybe, I would like more details',
                'target_school_types' => [
                    'Secondary Schools',
                    'Vocational and Technical Schools'
                ],
                'digital_expertise_areas' => [
                    'STEM/STEAM education',
                    'Digital Education and EdTech',
                    'Artificial Intelligence & Machine Learning'
                ],
                'want_updates' => true,
                'description' => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach($records as $record) {
            MatchmakingProfile::create($record);
        }
    }
}
