<?php

namespace Database\Seeders;

use App\MatchmakingProfile;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Carbon\Carbon;

class MatchmakingProfilesSeeder2 extends Seeder
{
    public function run()
    {
        $records = [
            [
                'start_time'  => Carbon::createFromFormat('n/j/y H:i:s', '6/7/25 7:14:59')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '6/7/25 7:20:50')->toDateTimeString(),
                'avatar'     => null,
                'email'      => 'arusyakivanyan@gmail.com',
                'get_email_from'      => null,
                'email_via_linkedin'  => false,
                'first_name' => 'Arusyak',
                'last_name'  => 'Ivanyan',
                'slug'       => Str::slug('Arusyak Ivanyan'),
                'languages'  => ['Armenia'],
                'job_title'  => '',
                'linkedin'   => 'https://www.linkedin.com/in/arusyak-ivanyan-b2a138b2',
                'organisation_type' => ['Non-Governmental Organisation (NGO)', 'Education/Training Provider', 'Academic Institution / Research Organisation'],
                'organisation_name' => 'Northern University',
                'website'    => '',
                'location'   => 'Armenia, Yerevan',
                'country'    => 'AM',
                'time_commitment' => ['Outside business hours', 'Short time'],
                'can_start_immediately' => true,
                'why_volunteering' => 'to gain new experience',
                'format'     => 'Online/Remote only',
                'support_activities' => ['Delivering workshops or training'],
                'is_use_resource' => false,
                'want_updates'    => true,
                'description'     => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_time'  => Carbon::createFromFormat('n/j/y H:i:s', '6/10/25 14:03:34')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '6/10/25 14:59:17')->toDateTimeString(),
                'avatar'     => null,
                'email'      => 'nstankova579@gmail.com',
                'get_email_from'      => null,
                'email_via_linkedin'  => false,
                'first_name' => 'Наталия',
                'last_name'  => 'Станкова',
                'slug'       => Str::slug('nstankova 579'),
                'languages'  => ['Bulgarian'],
                'job_title'  => 'старши учител',
                'linkedin'   => '',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'СУ "Цветан Радославов" - гр.Свищов',
                'website'    => '',
                'location'   => 'България, Свищов',
                'country'    => 'BG',
                'time_commitment' => ['Outside business hours','Short time'],
                'can_start_immediately' => true,
                'why_volunteering' => '"Code Week е важен защото:\n*Развива дигитални умения: В днешния свят дигиталните умения, включително програмирането, са от съществено значение. Code Week помага на хората да ги придобият по забавен и достъпен начин.\n*Насърчава креативността и решаването на проблеми: Кодирането не е само писане на код, а е и начин за мислене, който развива креативността и способността за решаване на сложни проблеми.\n*Достъпност за всички: Инициативата цели да направи програмирането достъпно за хора от всички възрасти и произход, като разрушава бариерите и демистифицира тези умения.\n*Изгражда общност: Code Week свързва хора с общ интерес към програмирането и дигиталните умения, създавайки подкрепяща общност, която си обменя знания и идеи.\nДоброволците са сърцето на Code Week. Те са учители, ментори, родители, специалисти от ИТ сектора и други ентусиасти, които посвещават времето и енергията си на инициативата\nАз искам да го правя, защото:\n*Вярвам във важността на дигиталното образование: Осъзнавам, че програмирането е ключово умение за бъдещето и искам да го предавам на следващите поколения.\n*Искам да вдъхновявам: Ще се стремя да покажа на младите хора, че програмирането може да бъде вълнуващо и креативно, и да ги вдъхновявам да създават.\n*Харесвам да споделям знания: За мен е удоволствие да предавам опита и знанията си, да обучавам и да виждам как другите развиват нови умения.\n* Да съм част са от общност: Принадлежността към голяма, международна общност от съмишленици, които си сътрудничат и се подкрепят, е силна мотивация.\n*Желая да допринеса: Искам да имам положителен принос за обществото, като помагам за изграждането на дигитално грамотно население."',
                'format'     => 'Mentoring students or educators',
                'support_activities' => ['Online/Remote only'],
                'is_use_resource' => true,
                'want_updates'    => true,
                'description'     => 'За сега, не',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_time'  => Carbon::createFromFormat('n/j/y H:i:s', '14/7/25 19:07:00')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '14/7/25 19:14:00')->toDateTimeString(),
                'avatar'     => null,
                'email'      => 'gjananxhela@gmail.com',
                'get_email_from'      => null,
                'email_via_linkedin'  => false,
                'first_name' => 'Anxhela',
                'last_name'  => 'Gjana',
                'slug'       => Str::slug('Anxhela Gjana'),
                'languages'  => ['English', 'Italian'],
                'job_title'  => 'ICT TEACHER AND PROJECT MANAGER AT NGO',
                'linkedin'   => 'https://www.linkedin.com/in/anxhela-vincani-99b81810b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
                'organisation_type' => ['Education/Training Provider','Non-Governmental Organisation (NGO)'],
                'organisation_name' => 'school "Havzi Nela" and NGO "Ecologist for the region"',
                'website'    => '',
                'location'   => 'KUKES, ALBANIA',
                'country'    => 'AL',
                'time_commitment' => ['One-off','Short time'],
                'can_start_immediately' => true,
                'why_volunteering' => 'I love volunteering becouse here in Kukes is the only way to help youngs to empower.Its a way to help them understand more about technology and the right use for it.',
                'format'     => 'Both',
                'support_activities' => ['ICT', 'ARTIFICIAL INTELIGENCE','CYBERSECURITY','ENVIROMENTAL ACTIVITIES LIKE SUSTINABILITY','CIRCULAR ECONOMY'],
                'is_use_resource' => true,
                'want_updates'    => true,
                'description'     => 'I HAVE BEEN FOR 2 YEARS MENTOR OF THE PROGRAM AI FOR YOUTH,I HAVE BEEN A MENTOR FOR DIVERSE PROGRAMS LIKE CYBERSECURITY ,INOVATION FOR SOCIAL CHANGE ECT',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_time'  => Carbon::createFromFormat('n/j/y H:i:s', '26/7/25 10:21:00')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '26/7/25 10:30:00')->toDateTimeString(),
                'avatar'     => null,
                'email'      => 'scoalapi@yahoo.com',
                'get_email_from'      => null,
                'email_via_linkedin'  => false,
                'first_name' => 'Catalina',
                'last_name'  => 'Nicolin',
                'slug'       => Str::slug('Catalina Nicolin'),
                'languages'  => ['English','French','Italian','Romanian','Spanish'],
                'job_title'  => 'Digital skills trainer ICT and AI gen tools',
                'linkedin'   => 'https://www.linkedin.com/in/catalina-nicolin-66902b23?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
                'organisation_type' => ['Education/Training Provider'],
                'organisation_name' => 'APE',
                'website'    => '',
                'location'   => 'Romania, Bucharest',
                'country'    => 'RO',
                'time_commitment' => ['Short time','One-off'],
                'can_start_immediately' => true,
                'why_volunteering' => 'Is my passion training/teaching ICT, AI',
                'format'     => 'Online/Remote only',
                'support_activities' => ['MA in ICT in education','AI gen tools accredited Google'],
                'is_use_resource' => true,
                'want_updates'    => true,
                'description'     => '',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'start_time'  => Carbon::createFromFormat('n/j/y H:i:s', '2/8/25 18:25:00')->toDateTimeString(),
                'completion_time' => Carbon::createFromFormat('n/j/y H:i:s', '2/8/25 18:32:00')->toDateTimeString(),
                'avatar'     => null,
                'email'      => 'schaida_ferreira@hotmail.com',
                'get_email_from'      => null,
                'email_via_linkedin'  => false,
                'first_name' => 'Schaida',
                'last_name'  => 'Souza Ferreira Secco',
                'slug'       => Str::slug('Schaida Souza Ferreira Secco'),
                'languages'  => ['English','Italian','Portuguese','Spanish'],
                'job_title'  => 'Communications Assistant',
                'linkedin'   => 'https://www.linkedin.com/in/schaidaferreira/',
                'organisation_type' => ['Public Sector Organisation / Government Agency'],
                'organisation_name' => 'EU CAP Network',
                'website'    => '',
                'location'   => 'Brussels, Belgium',
                'country'    => 'BE',
                'time_commitment' => ['One-off', 'Outside business hours'],
                'can_start_immediately' => true,
                'why_volunteering' => 'Volunteering is a powerful way for me to support my personal growth while actively working toward my career goals. It offers the opportunity to develop valuable skills - such as communication, teamwork, and problem-solving - that are directly transferable to a professional environment. It also allows for hands-on experience in different roles or sectors, helping me clarify my career interests and aspirations. Beyond skill-building, volunteering demonstrates my initiative, commitment, and willingness to contribute beyond personal gain - qualities that are highly valued by employers. It is also a strategic way to strengthen my CV, especially as I continue to build experience and explore new professional paths. Moreover, it helps me expand my network and gain real-world insights through collaboration with experienced individuals. Perhaps most importantly, it builds my confidence and sense of purpose, allowing me to grow in meaningful ways while making a positive impact.',
                'format'     => 'Both',
                'support_activities' => ['I am an International Relations Communicator. I have expertise in communications, copywriting, public speaking, graphic design, social media and event management (both in person and online).'],
                'is_use_resource' => true,
                'want_updates'    => true,
                'description'     => 'I speak English, Portuguese, Spanish and Italian fluently. I believe it can be an asset if I need to communicate with European students and or educators.',
                'agree_to_be_contacted_for_feedback' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach($records as $record) {
            MatchmakingProfile::create($record);
        }
    }
}
