<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\ResourceRequest
 */
class ResourceRequestTest extends TestCase
{
    /** @var \App\Http\Requests\ResourceRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\ResourceRequest();
    }

    /**
     * @test
     */
    public function authorize(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'name' => 'required',
            'source' => 'required',
            'description' => 'required',
        ], $actual);
    }

    /**
     * @test
     */
    public function messages(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->messages();

        $this->assertEquals([
            'name.required' => 'Please enter a name for your resource.',
            'source.required' => 'Please enter the URL of the resource.',
            'description.required' => 'Please write a short description of what the resource is about.',
        ], $actual);
    }

    // test cases...
}
