<?php


return [
    'when-title' => 'V&nbsp;roku 2019 sa Eur&oacute;psky t&yacute;ždeň programovania kon&aacute; od 5.&nbsp;do 20.&nbsp;okt&oacute;bra>.',
    'when-text' => '<p>Eur&oacute;psky t&yacute;ždeň programovania je nez&aacute;visl&eacute; hnutie, ktor&eacute; oslavuje tvorivosť, rie&scaron;enie probl&eacute;mov a spolupr&aacute;cu prostredn&iacute;ctvom programovania a ďal&scaron;&iacute;ch technologick&yacute;ch aktiv&iacute;t. Z&aacute;merom je viac zviditeľniť programovanie, uk&aacute;zať mlad&yacute;m, dospel&yacute;m a star&scaron;&iacute;m ľuďom, ako vd&yacute;chnuť život n&aacute;padom pomocou programovania, r&uacute;cať m&yacute;ty o&nbsp;t&yacute;chto zručnostiach a spojiť motivovan&yacute;ch ľud&iacute;, aby sa spolu vzdel&aacute;vali.</p>',
    'codeweek_in_numbers-title' => 'T&yacute;ždeň programovania v&nbsp;č&iacute;slach',
    'codeweek_in_numbers-text' => '<p>V roku 2018 sa Európskeho týždňa programovanie zúčastnilo 2,7 milióna ľudí vo viac ako 70 krajinách celého sveta. Ďalších 2,3 milióna mladých ľudí sa zapojilo do <a href="http://africacodeweek.org/">Africk&eacute;ho t&yacute;ždňa programovania</a>, čo je spin-off iniciatíva, ktorú organizuje SAP a iné neziskové organizácie.</p>
                    <p>Ak sa va&scaron;a krajina e&scaron;te nezapojila, m&ocirc;žete usporiadať aktivity a zaznamenať ich na <a href="/events">mape</a> alebo sa m&ocirc;žete <a href="mailto:info@codeweek.eu">prihl&aacute;siť ako dobrovoľn&iacute;k</a> a stať sa veľvyslancom T&yacute;ždňa programovania.</p>',
    'run_by_volunteers-title' => 'Hnutie dobrovoľn&iacute;kov',
    'run_by_volunteers-text' => '<p>Eur&oacute;psky t&yacute;ždeň programovania organizuj&uacute; dobrovoľn&iacute;ci. Jeden či niekoľk&iacute; <a href="/ambassadors">veľvyslanci T&yacute;ždňa programovania</a> koordinuj&uacute; iniciat&iacute;vu vo svojej vlasti, no ktokoľvek m&ocirc;že usporiadať vlastn&uacute; program&aacute;torsk&uacute; aktivitu a&nbsp;pridať ju na mapu na str&aacute;nke <a href="/">codeweek.eu</a>.</p>',
    'supported_by_commission-title' => 'S&nbsp;podporou Eur&oacute;pskej komisie',
    'supported_by_commission-text' => '<p>Eur&oacute;psky t&yacute;ždeň programovania rozpr&uacute;dili v&nbsp;roku 2013 mlad&iacute; poradcovia pre Digit&aacute;lnu agendu Eur&oacute;py. Eur&oacute;pska komisia podporuje Eur&oacute;psky t&yacute;ždeň programovania v&nbsp;r&aacute;mci svojej strat&eacute;gie v&nbsp;oblasti <a href="http://ec.europa.eu/priorities/digital-single-market/">jednotn&eacute;ho digit&aacute;lneho trhu</a>. V&nbsp;<a href="https://ec.europa.eu/education/initiatives/european-education-area/digital-education-action-plan_en">akčnom pl&aacute;ne digit&aacute;lneho vzdel&aacute;vania</a> Komisia osobitne &scaron;koly podnecuje, aby sa zapojili do tejto iniciat&iacute;vy. Cieľom je dosiahnuť 50&nbsp;% &uacute;časť v&scaron;etk&yacute;ch &scaron;k&ocirc;l v&nbsp;Eur&oacute;pe do roku 2020.</p>',
    'schools-title' => '&Scaron;koly',
    'schools-text' => '<p>&Scaron;koly na v&scaron;etk&yacute;ch &uacute;rovniach a učitelia v&scaron;etk&yacute;ch predmetov s&uacute; osobitne vyzvan&iacute;, aby sa zapojili do Eur&oacute;pskeho t&yacute;ždňa programovania, čo umožn&iacute; ich &scaron;tudentom zozn&aacute;miť sa s&nbsp;digit&aacute;lnou tvorivosťou a programovan&iacute;m. Ďal&scaron;ie inform&aacute;cie o&nbsp;iniciat&iacute;ve a n&aacute;vod na usporiadanie aktivity n&aacute;jdete na na&scaron;ej webovej str&aacute;nke pre učiteľov: <a href="/schools">CodeWeek.eu/Schools</a></p>',
    'why_coding-title' => 'Prečo programovanie?',
    'why_coding-text' => '<p>Je to o&nbsp;Pii, ktor&aacute; mala pocit, že mus&iacute; &scaron;tudovať pr&aacute;vo, hoci ju vždy bavila matematika a poč&iacute;tače. Je to o&nbsp;Markovi, ktor&yacute; m&aacute; n&aacute;pad na lep&scaron;iu soci&aacute;lnu sieť, ale nevie ju s&aacute;m vystavať. Je to o&nbsp;Alice, ktor&aacute; sn&iacute;va o&nbsp;tom, že bude vyr&aacute;bať roboty, pretože jej rodičia nedovolili mačku.</p>

                    <p>Je to o&nbsp;v&scaron;etk&yacute;ch v&aacute;s, ktor&iacute; už pom&aacute;hate, aby sa tieto sny stali skutočnosťou.</p>

                    <p>Vlastne je to o&nbsp;n&aacute;s v&scaron;etk&yacute;ch. O&nbsp;na&scaron;ej bud&uacute;cnosti. Technol&oacute;gie formuj&uacute; na&scaron;e životy, a pritom len men&scaron;inu nech&aacute;vame rozhodovať o&nbsp;tom, na čo a ako ich využ&iacute;vame. Dok&aacute;žeme viac než len zdieľať a hodnotiť pr&iacute;spevky. M&ocirc;žeme vd&yacute;chnuť život na&scaron;im bl&aacute;zniv&yacute;m n&aacute;padom, vybudovať veci, ktor&eacute; prines&uacute; radosť ostatn&yacute;m.</p>

                    <p>Nikdy nebolo jednoduch&scaron;ie vytvoriť vlastn&uacute; aplik&aacute;ciu, vyrobiť si robota, či dokonca vymyslieť lietaj&uacute;ce aut&aacute;, veď prečo nie! Nie je to jednoduch&aacute; cesta, no je to cesta pln&aacute; tvoriv&yacute;ch v&yacute;ziev s&nbsp;komunitou pripravenou pom&ocirc;cť a kopou z&aacute;bavy. Ste pripraven&iacute; prijať v&yacute;zvu a stať sa tvorcom?</p>

                    <p>Programovanie tiež pom&aacute;ha rozv&iacute;jať schopnosti, ako s&uacute; v&yacute;počtov&eacute; myslenie, rie&scaron;enie probl&eacute;mov, tvorivosť a t&iacute;mov&aacute; pr&aacute;ca, čo s&uacute; v&yacute;born&eacute; zručnosti pre v&scaron;etky oblasti života.</p>',
    'why_coding-quote' => '<p>Alessandro Bogliolo, koordin&aacute;tor t&iacute;mu veľvyslancov-dobrovoľn&iacute;kov Eur&oacute;pskeho t&yacute;ždňa programovania, uviedol:<blockquote>
                            <p>&bdquo;Od nepam&auml;ti vytv&aacute;rame r&ocirc;zne veci, ktor&eacute; zmenili n&aacute;&scaron; život, pomocou kameňa, železa, papiera a ceruzky. Teraz žijeme v&nbsp;inej dobe, v&nbsp;ktorej sa n&aacute;&scaron; svet premieta do programovac&iacute;ch v&yacute;razov. V&nbsp;r&ocirc;znych dob&aacute;ch sa dopyt po jednotliv&yacute;ch pracovn&yacute;ch miestach a zručnostiach l&iacute;&scaron;i. Počas t&yacute;ždňa programovania chceme dať v&scaron;etk&yacute;m Eur&oacute;panom &scaron;ancu, aby objavili programovanie a zažili pri tom veľa z&aacute;bavy. Naučme sa programovať a pretvorme na&scaron;u bud&uacute;cnosť.&ldquo;</p>
                        </blockquote>
                    </p>',
    'join_codeweek-title' => 'Zapojte sa do Eur&oacute;pskeho t&yacute;ždňa programovania',
    'join_codeweek-text' => '<p>Zapojte sa do Eur&oacute;pskeho t&yacute;ždňa programovania <a href="/guide">usporiadan&iacute;m program&aacute;torskej aktivity</a> vo svojom meste, zapojen&iacute;m do <a href="/codeweek4all">v&yacute;zvy Code Week 4 All</a> a pr&iacute;buzn&yacute;ch aktiv&iacute;t v&nbsp;r&ocirc;znych komunit&aacute;ch a krajin&aacute;ch alebo n&aacute;m pom&ocirc;žte &scaron;&iacute;riť v&iacute;ziu T&yacute;ždňa programovania z&nbsp;poz&iacute;cie <a href="/ambassadors">veľvyslanca Eur&oacute;pskeho t&yacute;ždňa programovania</a> vo svojej vlasti!</p>'
];
