<?php

return [

    'title' => 'ZA&Scaron;TITA VA&Scaron;IH OSOBNIH PODATAKA',
    '1-intro' => [
        'title' => '1. Uvod','items' => ['1' => '<p>Evropska komisija (u daljem tekstu: Komisija) opredijeljena je za za&scaron;titu va&scaron;ih osobnih podataka i za po&scaron;tovanje va&scaron;e privatnosti. Komisija prikuplja i dalje obrađuje osobne podatke u skladu sa Uredbom (EU) 2018/1725 Evropskog parlamenta i Vijeća od 23. oktobra 2018. o za&scaron;titi fizičkih lica u pogledu obrade osobnih podataka od strane institucija, tijela, ureda i agencija Unije i o slobodnom kretanju takvih podataka (čime se poni&scaron;tava Uredba (EC) br. 45/2001).</p>','2' => '<p>U ovoj izjavi o privatnosti poja&scaron;njava se razlog za prikupljanje i obradu, način na koji mi prikupljamo i obrađujemo sve dostavljene osobne podatke, te osiguravamo njihovu za&scaron;titu, kako se te informacije koriste i koja prava vi eventualno vr&scaron;ite u odnosu na svoje osobne podatke (pravo pristupa, korekcije, blokiranja, itd),  Njome se također preciziraju pojedinosti o odgovornom kontroloru podataka s kojim možete vr&scaron;iti svoja prava, referentu za za&scaron;titu podataka i evropskom nadzorniku za za&scaron;titu podataka.</p>','3' => '<p>Ova izjava o privatnosti tiče se prikupljanja i objavljivanja osobnih podataka na javno pristupačnoj internet stranici Codeweek.eu o licima koja služe kao tačke kontakta za aktivnosti u okviru Sedmice kodiranja EU (ambasadori Sedmice kodiranja, koordinatori u ministarstvima obrazovanja, vodeći nastavnici, kao i organizatori aktivnosti i de&scaron;avanja).</p>',]
    ],
    '2-why' => [
        'title' => '2. Za&scaron;to mi obrađujemo va&scaron;e podatke?','items' => ['1' => '<p>Evropska komisija prikuplja i objavljuje va&scaron;e osobne informacije kako bi olak&scaron;ala interesnim stranama ili zainteresiranim građanima identificiranje tački kontakta. Nuđenje stvarnih osoba kao tački kontakta je najbolji i najefikasniji način da se osigura da zainteresirana lica stupe u kontakt sa službama Komisije.</p>','2' => '<p>Va&scaron;i osobni podaci neće se koristiti ni za kakvo automatizirano odlučivanje, uključujući profiliranje.</p>',]
    ],
    '3-legal_process' => [
        'title' => '3. Na kom pravnom temelju (temeljima) obrađujemo va&scaron;e osobne podatke','items' => ['1' => '<p>Operacije obrade na osobnim podacima za objavljivanje tački kontakta zakonite su po članu 5(1)(d) Uredbe (EU) 2018/1725, jer ste vi dali pristanak na obradu svojih osobnih podataka putem internet  formulara ili kada ste se složili da mi koristimo va&scaron;u e-po&scaron;tu i korisničko ime ako ste se prijavljivali putem dru&scaron;tvene mreže. </p>',]
    ],
    '4-collect_data' => [
        'title' => '4. Koje osobne podatke prikupljamo i dalje obrađujemo?','items' => ['1' => '<p>Osobni podaci koji se prikupljaju su informacije kojima se va&scaron;a identifikacija kao tačke kontakta olak&scaron;ava i kojima se povećava va&scaron;a vidljivost za javnost, naime: naslov, ime, prezime, pozicija, profesionalna po&scaron;tanska adresa i adresa e-po&scaron;te, telefonski broj, slika, račun dru&scaron;tvenih medija, biografija. </p>','2' => '<p>Vi ste dali te osobne podatke na dobrovoljnoj osnovi popunjavanjem prijavnog formulara.</p>','3' => '<p>Davanje određenih osobnih podataka obavezno je za objavljivanje aktivnosti i/ili kontakt informacija na internet stranici codeweek.eu.  Ako ne budete dali svoje osobne podatke, va&scaron;a aktivnost neće biti objavljena i/ili vi nećete moći učestvovati u gore navedenim mrežama.</p>','4' => '<p>Sve ostale osobne podatke dajete na dobrovoljnoj osnovi.</p>',]
    ],
    '5-how_long' => [
        'title' => '5. Koliko dugo držimo va&scaron;e osobne podatke?','items' => ['1' => '<p>Komisija drži va&scaron;e osobne podatke samo onoliko dugo koliko je neophodno u svrhu prikupljanja ili daljnje obrade &scaron;to je opisano u tački 2, naime onoliko dugo koliko vi služite kao tačka kontakta.</p>','2' => '<p>Va&scaron;i osobni podaci će biti uklonjeni sa javno dostupne internet stranice čim vi prestanete biti na svojoj funkciji tačke kontakta, osim ako niste dali pristanak da budete uključeni u bazu podataka za buduće aktivnosti.</p>',]
    ],
    '6-protect_data' => [
        'title' => '6. Kako mi &scaron;titimo i čuvamo va&scaron;e osobne podatke?','items' => ['1' => '<p>Svi osobni podaci u elektronskom obliku (e-po&scaron;ta, dokumenti, baze podataka, učitane serije podataka, itd.) pohranjuju se na servere Evropske komisije ili njenog ugovornog izvođača. Sve operacije obrade vr&scaron;e se u skladu sa Odlukom Komisije (EU, Euratom) 2017/46 od 10. januara 2017. o sigurnosti komunikacijskih i informacijskih sistema u Evropskoj komisiji.</p>','2' => '<p>Ugovorni izvođači Komisije obavezani su posebnom ugovornom klauzulom po pitanju svih evenualnih operacija obrade va&scaron;ih podataka u ime Komisije, te obavezama povjerljivosti koje proističu iz transpozicije Op&scaron;te uredbe o za&scaron;titi podataka u državama članicama EU (Uredba &quot;GDPR&quot; (EU) 2016/679).</p>','3' => '<p>U cilju za&scaron;tite va&scaron;ih osobnih podataka, Komisija je uspostavila niz tehničkih i organizacionih mjera. Tehničke mjere uključuju odgovarajuće akcije u cilju rada na rje&scaron;avanju online sigurnosti, rizika od gubljenja podataka, mijenjanja podataka ili neovla&scaron;tenog pristupa, uzimajući u obzir rizik koji je posljedica obrade i prirodu osobnih podataka koji se obrađuju. Organizacione mjere uključuju ograničavanje pristupa osobnim podacima samo na ovla&scaron;tena lica sa legitimnom potrebom da znaju koja je svrha ove operacije obrade.</p>',]
    ],
    '7-access_data' => [
        'title' => '7. Ko ima pristup va&scaron;im podacima i kome se oni otkrivaju?','items' => ['1' => '<p>Pristup va&scaron;im osobnim podacima je omogućen osoblju Komisije nadležnom za vr&scaron;enje ove operacije obrade i ovla&scaron;tenom osoblju u skladu sa principom &quot;potrebe za saznanjem&quot;. To osoblje pridržava se zakonskih, a po potrebi i dodatnih ugovora o povjerljivosti.</p>','2' => '<p>Konkretno, svim osobnim podacima koje dostavite mogu pristupiti administratori internet stranica (osoblje Komisije), kao i drugo osoblje Komisije na temelju potrebe za saznanjem. . Osim toga, va&scaron;e osobne informacije i informacije o de&scaron;avanjima će se podijeliti sa članovima mreža ambasadora i obrazovnih koordinatora Sedmice kodiranja EU za organizaciju lokalnih aktivnosti ili naknadni rad na njima. </p>','3' => '<p>U svrhu povećanja vidljivosti tački kontakta, va&scaron;i osobni podaci se objavljuju bez ikakvog ograničenja pristupa na javnoj internet stranici: https://codeweek.eu.</p>','4' => '<p><i>Pitanje prijenosa podataka trećim licima</i></p>','5' => '<p>Informacije koje mi prikupljamo neće se davati nijednom trećem licu, osim u onom obimu i u svrhu za koju to budemo po zakonu obavezni uraditi.</p>',]
    ],
    '8-rights' => [
        'title' => '8. Kakva su va&scaron;a prava i kako ih možete vr&scaron;iti?','items' => ['1' => '<p>Vi imate posebna prava kao &quot;subjekt podataka&quot; po Poglavlju III (članovi 14-25) Uredbe (EU) 2018/1725, a posebno pravo na pristup, korekciju ili brisanje svojih osobnih podataka, te pravo na ograničavanje obrade svojih osobnih podataka. Gdje je to relevatno, imate i pravo na ulaganje prigovora na obradu ili pravo na prenosivost podataka.</p>','2' => '<p>Vi ste pristali na dostavljanje svojih osobnih podataka za postojeću operaciju obrade i možete u svako vrijeme povući svoj pristanak dostavom obavijesti kontroloru podataka. Povlačenjem se neće utjecati na zakonitost obrade koja je izvr&scaron;ena prije nego &scaron;to ste vi povukli pristanak.</p>','3' => '<p>Vi možete vr&scaron;iti svoja prava tako &scaron;to ćete kontaktirati kontrolora podataka, ili u slučaju sukoba, referenta za za&scaron;titu podataka. U slučaju da je to neophodno, možete se obratiti i evropskom nadzorniku za za&scaron;titu podataka. Njihove kontakt informacije date su pod Naslovom 9. u nastavku.</p>',]
    ],
    '9-contact' => [
        'title' => '9. Kontakt informacije',
        'data-controller' => [
            'title'=>'-Kontrolor podataka',
            'text' => '<p>Ako želite vr&scaron;iti svoja prava po Uredbi (EU) 2018/1725, ili ako imate komentare, pitanja ili molbe, ili ako biste htjeli podnijeti pritužbu po pitanju prikupljanja i upotrebe svojih osobnih podataka, slobodno se obratite kontroloru podataka,</p>',
            'address' => 'Jedinica Generalne direkcije za komunikacijske mreže, sadržaj i tehnologiju F4<br> Zgrada BU25<br> B-1049 Brisel<br>',
            'email' => 'E-po&scaron;ta: '
        ],
        'data-protection-officer' => [
            'title' => '- Referent za za&scaron;titu podataka (DPO) Komisije',
            'text' => '<p>Možete kontaktirati referenta za za&scaron;titu podataka (<a href="mailto:DATA-PROTECTION-OFFICER@ec.europa.eu">DATA-PROTECTION-OFFICER@ec.europa.eu</a>) u vezi pitanja vezanih za obradu va&scaron;ih osobnih podataka po Uredbi (EU) 2018/1725.</p>'
        ],
        'european-data-protection' => [
            'title' => '-Evropski nadzornik za za&scaron;titu podataka (EDPS)',
            'text' => '<p>Imate pravo na pravni lijek (tj. možete uložiti pritužbu) evropskom nadzorniku za za&scaron;titu podataka (<a href="mailto:edps@edps.europa.eu">edps@edps.europa.eu</a>) ako smatrate da su va&scaron;a prava po Uredbi (EU) 2018/1725 naru&scaron;ena kao rezultat obrade va&scaron;ih osobnih podataka od strane kontrolora podataka.</p>'
        ]
    ]
];
