<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AdminController
 */
class AdminControllerTest extends TestCase
{
    /**
     * @test
     */
    public function activities_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('activities'));

        $response->assertOk();
        $response->assertViewIs('activities');
        $response->assertViewHas('activities');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function certificates_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin_certificates'));

        $response->assertOk();
        $response->assertViewIs('admin.certificates');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function generate_certificates_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('generate_certificates'), [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertViewIs('admin.certificates');
        $response->assertViewHas('results');

        // TODO: perform additional assertions
    }

    // test cases...
}
