<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\CertificateController
 */
class CertificateControllerTest extends TestCase
{
    /**
     * @test
     */
    public function list_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('certificates'));

        $response->assertOk();
        $response->assertViewIs('certificates');
        $response->assertViewHas(['reported_events', 'excellence', 'participation', 'superOrganiser']);

        // TODO: perform additional assertions
    }

    // test cases...
}
