<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Codeweek4AllController
 */
class Codeweek4AllControllerTest extends TestCase
{
    /**
     * @test
     */
    public function detail_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('codeweek4all_details', ['code' => $code]));

        $response->assertOk();
        $response->assertViewIs('codeweek4all.detail');
        $response->assertViewHas(['result', 'countries', 'initiator']);

        // TODO: perform additional assertions
    }

    // test cases...
}
