<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\CodingAtHomeController
 */
class CodingAtHomeControllerTest extends TestCase
{
    /**
     * @test
     */
    public function show_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('coding@home'));

        $response->assertOk();
        $response->assertViewIs('codingathome.codingathome');

        // TODO: perform additional assertions
    }

    // test cases...
}
