<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\CommunityController
 */
class CommunityControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $users = \App\User::factory()->times(3)->create();

        $response = $this->get(route('ambassadors'));

        $response->assertRedirect('community?country_iso='.$country_iso);

        // TODO: perform additional assertions
    }

    // test cases...
}
