<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\EmailController
 */
class EmailControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $event = \App\Event::factory()->create();
        $users = \App\User::factory()->times(3)->create();

        $response = $this->get('mail/{event}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
