<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ExcellenceWinnersController
 */
class ExcellenceWinnersControllerTest extends TestCase
{
    /**
     * @test
     */
    public function excel_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('excellence_excel'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function list_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('excellence_winners'));

        $response->assertOk();
        $response->assertViewIs('excellence.winners');
        $response->assertViewHas(['edition', 'details', 'total_events', 'total_reported', 'percentage_reported']);

        // TODO: perform additional assertions
    }

    // test cases...
}
