<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\LeadingTeacherController
 */
class LeadingTeacherControllerTest extends TestCase
{
    /**
     * @test
     */
    public function get_current_toolkit_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('leading-teachers-document'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
