<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\LeadingTeachersList
 */
class LeadingTeachersListTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('leading_teachers_list'));

        $response->assertOk();
        $response->assertViewIs('leading-teachers.admin.list');

        // TODO: perform additional assertions
    }

    // test cases...
}
