<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\LeadingTeachersSignup
 */
class LeadingTeachersSignupTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('LT.signup'));

        $response->assertOk();
        $response->assertViewIs('leading-teachers.signup-form');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('LT.signup.store'), [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertViewIs('leading-teachers.signup-form-success');

        // TODO: perform additional assertions
    }

    // test cases...
}
