<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MapController
 */
class MapControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('map'));

        $response->assertOk();
        $response->assertViewIs('map');
        $response->assertViewHas('years');
        $response->assertViewHas('selectedYear');
        $response->assertViewHas('current_country_iso');

        // TODO: perform additional assertions
    }

    // test cases...
}
