<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\OnlineEventsController
 */
class OnlineEventsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function calendar_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('featured_activities'));

        $response->assertOk();
        $response->assertViewIs('online-calendar.oc-index');
        $response->assertViewHas('events');
        $response->assertViewHas('countries');
        $response->assertViewHas('countryNames');
        $response->assertViewHas('languages');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function featured_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $country = \App\Country::factory()->create();

        $response = $this->get(route('featured_events'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function list_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $country = \App\Country::factory()->create();

        $response = $this->get(route('online_events_by_country', [$country]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function promoted_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $country = \App\Country::factory()->create();

        $response = $this->get(route('promoted_events'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
