<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ParticipationController
 */
class ParticipationControllerTest extends TestCase
{
    /**
     * @test
     */
    public function generate_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('participation_submit'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('certificates'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('participation'));

        $response->assertOk();
        $response->assertViewIs('participation.index');

        // TODO: perform additional assertions
    }

    // test cases...
}
