<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ReportController
 */
class ReportControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $event = \App\Event::factory()->create();

        $response = $this->get(route('report_event', [$event]));

        $response->assertOk();
        $response->assertViewIs('report.index');
        $response->assertViewHas('event', $event);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function list_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('my_reportable_events'));

        $response->assertOk();
        $response->assertViewIs('report.list');
        $response->assertViewHas('events');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $event = \App\Event::factory()->create();

        $response = $this->post('event/report/{event}', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertViewIs('report.thankyou');
        $response->assertViewHas('event', $event);

        // TODO: perform additional assertions
    }

    // test cases...
}
