<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ReviewController
 */
class ReviewControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $country = \App\Country::factory()->create();

        $response = $this->get(route('review_by_country', [$country]));

        $response->assertOk();
        $response->assertViewIs('review');

        // TODO: perform additional assertions
    }

    // test cases...
}
