<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SchoolsController
 */
class SchoolsControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('schools'));

        $response->assertOk();
        $response->assertViewIs('schools');
        $response->assertViewHas('questions');

        // TODO: perform additional assertions
    }

    // test cases...
}
