<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ScoreboardController
 */
class ScoreboardControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('scoreboard'));

        $response->assertOk();
        $response->assertViewIs('scoreboard');
        $response->assertViewHas('events');
        $response->assertViewHas('total');
        $response->assertViewHas('edition');
        $response->assertViewHas('years');

        // TODO: perform additional assertions
    }

    // test cases...
}
