<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SearchController
 */
class SearchControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function search_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $country = \App\Country::factory()->create();

        $response = $this->get(route('events_map'));

        $response->assertOk();
        $response->assertViewIs('event.search');
        $response->assertViewHas(['query', 'years', 'selected_country', 'selected_year', 'tag']);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function search_p_o_s_t_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('search_events'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
