<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\StaticPageController
 */
class StaticPageControllerTest extends TestCase
{
    /**
     * @test
     */
    public function static_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('guide'));

        $response->assertOk();
        $response->assertViewIs('static.'.$routeName);

        // TODO: perform additional assertions
    }

    // test cases...
}
