<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SuperOrganiserController
 */
class SuperOrganiserControllerTest extends TestCase
{
    /**
     * @test
     */
    public function generate_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('certificate_super_organiser_report', ['edition' => $edition]), [
            // TODO: send request data
        ]);

        $response->assertRedirect('certificates');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function generate_aborts_with_a_403(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        // TODO: perform additional setup to trigger `abort(403)`...

        $response = $this->post(route('certificate_super_organiser_report', ['edition' => $edition]), [
            // TODO: send request data
        ]);

        $response->assertForbidden();
    }

    /**
     * @test
     */
    public function report_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('certificate_super_organiser', ['edition' => $edition]));

        $response->assertOk();
        $response->assertViewIs('super-organiser.report');
        $response->assertViewHas('edition');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function report_aborts_with_a_403(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        // TODO: perform additional setup to trigger `abort(403)`...

        $response = $this->get(route('certificate_super_organiser', ['edition' => $edition]));

        $response->assertForbidden();
    }

    // test cases...
}
