<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ToolkitsController
 */
class ToolkitsControllerTest extends TestCase
{
    /**
     * @test
     */
    public function get_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('toolkits'));

        $response->assertOk();
        $response->assertViewIs('toolkits');
        $response->assertViewHas(['locale']);

        // TODO: perform additional assertions
    }

    // test cases...
}
