<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\UnsubscribeController
 */
class UnsubscribeControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\User::factory()->create();

        $response = $this->get(route('unsubscribe', ['email' => $email, 'magic' => $magic]));

        $response->assertOk();
        $response->assertViewIs('unsubscribed');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_aborts_with_a_403(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\User::factory()->create();

        // TODO: perform additional setup to trigger `abort(403)`...

        $response = $this->get(route('unsubscribe', ['email' => $email, 'magic' => $magic]));

        $response->assertForbidden();
    }

    // test cases...
}
