<?php


return [
    'when-title'=> 'V roce 2019 proběhne Evropsk&yacute; t&yacute;den programov&aacute;n&iacute; od 5. do 20. ř&iacute;jna.',
    'when-text'=>'<p>Evropsk&yacute; t&yacute;den programov&aacute;n&iacute; je projekt, kter&yacute; propaguje kreativitu, ře&scaron;en&iacute; probl&eacute;mů a spolupr&aacute;ci pomoc&iacute; programov&aacute;n&iacute; a jin&yacute;ch technick&yacute;ch aktivit. C&iacute;lem je programov&aacute;n&iacute; zviditelnit &ndash; uk&aacute;zat mlad&yacute;m lidem, dospěl&yacute;m i seniorům, jak je d&iacute;ky programov&aacute;n&iacute; možn&eacute; realizovat my&scaron;lenky. Chceme tyto dovednosti zbavit rou&scaron;ky tajemstv&iacute; a spojit motivovan&eacute; lidi, aby se učili.</p>',
    'codeweek_in_numbers-title'=>'T&yacute;den programov&aacute;n&iacute; v č&iacute;slech',
    'codeweek_in_numbers-text'=>'<p>V roce 2018 se Evropsk&eacute;ho t&yacute;dne programov&aacute;n&iacute; z&uacute;častnilo 2,7 milionu lid&iacute; ve v&iacute;ce než 70 zem&iacute;ch cel&eacute;ho světa. Dal&scaron;&iacute;ch 2,3 milionu mlad&yacute;ch lid&iacute; se zapojilo do <a href="http://africacodeweek.org/">Africk&eacute;ho t&yacute;dne programov&aacute;n&iacute;</a>, což je spin-off iniciativa, kterou provozuje SAP a dal&scaron;&iacute; neziskov&eacute; organizace.</p>
                    <p>Pokud se va&scaron;e země je&scaron;tě nezapojila, můžete zorganizovat akce a přidat je na <a href="/events">mapu</a> nebo se zapojit jako <a href="mailto:info@codeweek.eu">dobrovoln&iacute;k</a> a st&aacute;t se ambasadorem t&yacute;dne programov&aacute;n&iacute;.</p>',
    'run_by_volunteers-title'=>'Organizov&aacute;no dobrovoln&iacute;ky',
    'run_by_volunteers-text'=>'<p>Evropsk&yacute; t&yacute;den programov&aacute;n&iacute; organizuj&iacute; dobrovoln&iacute;ci. Jeden nebo několik <a href="/ambassadors">ambasadorů t&yacute;dne programov&aacute;n&iacute;</a> koordinuje tuto iniciativu ve sv&eacute; zemi, ale vlastn&iacute; akci může zorganizovat každ&yacute; a přidat ji na mapu na str&aacute;nk&aacute;ch <a href="/">codeweek.eu</a>.</p>',
    'supported_by_commission-title'=>'Projekt m&aacute; podporu Evropsk&eacute; komise',
    'supported_by_commission-text'=>'<p>Evropsk&yacute; t&yacute;den programov&aacute;n&iacute; zah&aacute;jili v roce 2013 mlad&iacute; poradci pro evropskou digit&aacute;ln&iacute; agendu. Evropsk&aacute; komise podporuje Evropsk&yacute; t&yacute;den programov&aacute;n&iacute; jako souč&aacute;st sv&eacute; strategie <a href="http://ec.europa.eu/priorities/digital-single-market/">digit&aacute;ln&iacute;ho jednotn&eacute;ho trhu</a>. V r&aacute;mci <a href="https://ec.europa.eu/education/initiatives/european-education-area/digital-education-action-plan_en">Akčn&iacute;ho pl&aacute;nu digit&aacute;ln&iacute;ho vzděl&aacute;v&aacute;n&iacute;</a> komise povzbuzuje zvl&aacute;&scaron;tě &scaron;koly, aby se k t&eacute;to iniciativě připojily. C&iacute;lem je, aby se do roku 2020 zapojilo 50&nbsp;% v&scaron;ech evropsk&yacute;ch &scaron;kol.</p>',
    'schools-title'=>'&Scaron;koly',
    'schools-text'=>'<p>&Scaron;koly v&scaron;ech stupňů a učitel&eacute; bez ohledu na to, kter&eacute; předměty vyučuj&iacute;, jsou zvl&aacute;&scaron;tě zv&aacute;ni, aby se Evropsk&eacute;ho t&yacute;dne programov&aacute;n&iacute; z&uacute;častnili a dali tak sv&yacute;m ž&aacute;kům př&iacute;ležitost prozkoumat digit&aacute;ln&iacute; kreativitu a programov&aacute;n&iacute;. V&iacute;ce informac&iacute; o iniciativě a o tom, jak svou akci zorganizovat, najdete na webov&eacute; str&aacute;nce pro učitele: <a href="/schools">CodeWeek.eu/Schools</a></p>',
    'why_coding-title'=>'Proč programov&aacute;n&iacute;?',
    'why_coding-text'=>'<p>Př&iacute;kladem je Pia, kter&aacute; měla pocit, že mus&iacute; studovat pr&aacute;va, i když ji vždycky bavila matematika a poč&iacute;tače. Př&iacute;kladem je Mark, kter&yacute; vymyslel lep&scaron;&iacute; soci&aacute;ln&iacute; s&iacute;ť, ale nedok&aacute;že ji s&aacute;m vytvořit. Př&iacute;kladem je Alice, kter&aacute; sn&iacute; o tom, že bude vyr&aacute;bět roboty, protože j&iacute; rodiče nechtěj&iacute; dovolit, aby měla kočku.</p>

                    <p>Př&iacute;kladem jste vy v&scaron;ichni, kteř&iacute; se už snaž&iacute;te o to, aby se takov&eacute; sny staly skutečnost&iacute;.</p>

                    <p>Takže se to vlastně t&yacute;k&aacute; n&aacute;s v&scaron;ech. Jde o na&scaron;i budoucnost. Technologie formuj&iacute; na&scaron;i budoucnost, ale my nech&aacute;v&aacute;me jen několik jednotlivců, aby rozhodovali, co a jak budeme použ&iacute;vat. Můžeme dělat v&iacute;c, než jen něco sd&iacute;let a lajkovat. Svoje bl&aacute;zniv&eacute; n&aacute;pady můžeme přiv&eacute;st k životu a vytv&aacute;řet věci, kter&eacute; druh&yacute;m přinesou radost.</p>

                    <p>Nikdy nebylo snadněj&scaron;&iacute; vytvořit svou vlastn&iacute; appku, sestavit sv&eacute;ho vlastn&iacute;ho robota, nebo dokonce vymyslet l&eacute;taj&iacute;c&iacute; auto. Takže do toho! Cesta nebude snadn&aacute;, ale je pln&aacute; tvořiv&yacute;ch v&yacute;zev, ochotn&yacute;ch podporovatelů a spousty legrace. Jste ochotn&iacute; přijmout tuto v&yacute;zvu a st&aacute;t se tvůrcem?</p>

                    <p>Programov&aacute;n&iacute; tak&eacute; pom&aacute;h&aacute; rozv&iacute;jet dovednosti, jako je informatick&eacute; my&scaron;len&iacute;, ře&scaron;en&iacute; probl&eacute;mů, kreativita a t&yacute;mov&aacute; spolupr&aacute;ce &ndash; a to jsou dovednosti užitečn&eacute; pro v&scaron;echny oblasti života.</p>',
    'why_coding-quote'=>'<p>Alessandro Bogliolo, koordin&aacute;tor t&yacute;mu dobrovoln&iacute;ků Evropsk&eacute;ho t&yacute;dne programov&aacute;n&iacute;, řekl:<blockquote>
                            <p>&bdquo;Během dlouh&yacute;ch věků jsme mnoho věc&iacute;, kter&eacute; změnily n&aacute;&scaron; život, dok&aacute;zali udělat pomoc&iacute; kamene, železa, pap&iacute;ru a pera. Dnes žijeme v odli&scaron;n&eacute; době &ndash; n&aacute;&scaron; svět je formov&aacute;n programov&aacute;n&iacute;m. Různ&eacute; &eacute;ry maj&iacute; různ&eacute; požadavky na pracovn&iacute; odbornosti a dovednosti. Během T&yacute;dne programov&aacute;n&iacute; chceme d&aacute;t každ&eacute;mu Evropanovi př&iacute;ležitost objevit programov&aacute;n&iacute; a obl&iacute;bit si ho. Naučme se programovat a utv&aacute;řejme svou budoucnost.&ldquo;</p>
                        </blockquote>
                    </p>',
    'join_codeweek-title'=>'Zapojte se do Evropsk&eacute;ho t&yacute;dne programov&aacute;n&iacute;',
    'join_codeweek-text'=>'<p>Zapojte se do Evropsk&eacute;ho t&yacute;dne programov&aacute;n&iacute; tak, že ve sv&eacute;m městě <a href="/guide">zorganizujte programovac&iacute; akci</a>, zapoj&iacute;te se do <a href="/codeweek4all">soutěže Code Week 4 All</a> a souvisej&iacute;c&iacute;ch akc&iacute; např&iacute;č komunitami a hranicemi nebo n&aacute;m pomozte &scaron;&iacute;řit vizi T&yacute;dne programov&aacute;n&iacute; jako <a href="/ambassadors">ambasador Evropsk&eacute;ho t&yacute;dne programov&aacute;n&iacute;</a> ve sv&eacute; zemi!</p>'
];
