<?php

namespace Tests\Feature\Http\Controllers\Api;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Api\EventPictureController
 */
class EventPictureControllerTest extends TestCase
{
    /**
     * @test
     */
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('event_picture'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
